#!/usr/bin/env bash
# Print self-hosted version pins (Markdown) from live compose + Capgo repo.
# Usage: CAPGO_REPO=... SUPABASE_PROJECT_DIR=... bash scripts/collect-self-hosted-versions.sh
set -euo pipefail

CAPGO_REPO="${CAPGO_REPO:-$(cd "$(dirname "$0")/.." && pwd)}"
SUPABASE_PROJECT_DIR="${SUPABASE_PROJECT_DIR:-/root/supabase-project}"
COMPOSE="${SUPABASE_PROJECT_DIR}/docker-compose.yml"

log_section() { printf '\n## %s\n\n' "$1"; }

pkg_version() {
  local file="$1" key="$2"
  node -e "
    const p=require('${file}');
    const v=p.${key};
    console.log(v ?? '');
  " 2>/dev/null || true
}

app_ver="$(node -pe "require('${CAPGO_REPO}/package.json').version" 2>/dev/null || echo '?')"
cli_ver="$(node -pe "require('${CAPGO_REPO}/cli/package.json').version" 2>/dev/null || echo '?')"
git_rev="$(git -C "$CAPGO_REPO" rev-parse --short HEAD 2>/dev/null || echo '?')"
git_date="$(git -C "$CAPGO_REPO" log -1 --format='%ci' 2>/dev/null || echo '?')"

cat <<EOF
<!-- generated by collect-self-hosted-versions.sh — paste into docs/self-hosted-version-pins.zh-CN.md -->

| 元数据 | 值 |
| --- | --- |
| **生成时间** | $(date -u +%Y-%m-%dT%H:%M:%SZ) |
| **Capgo 提交** | \`${git_rev}\` (${git_date}) |
| **Capgo 应用** | \`${app_ver}\` |
| **@capgo/cli (workspace)** | \`${cli_ver}\` |
EOF

log_section "宿主机工具"
printf '| 组件 | 版本 |\n| --- | --- |\n'
for cmd_label in "Docker:docker --version" "Compose:docker compose version" "Bun:bun --version" "Python:python3 --version" "Nginx:nginx -v"; do
  label="${cmd_label%%:*}"
  cmd="${cmd_label#*:}"
  ver="$($cmd 2>&1 | head -1 | tr -d '\r' || echo '—')"
  printf '| %s | `%s` |\n' "$label" "$ver"
done

if [[ -f "$COMPOSE" ]]; then
  log_section "Supabase Docker 镜像"
  printf '| 服务（compose key） | 镜像 |\n| --- | --- |\n'
  awk '
    /^  [a-zA-Z0-9_.-]+:$/ { svc=$1; gsub(/:/,"",svc); next }
    /image:/ && svc != "" { printf "| %s | `%s` |\n", svc, $2; svc="" }
  ' "$COMPOSE"
else
  log_section "Supabase Docker 镜像"
  echo "未找到: $COMPOSE"
fi

log_section "Capgo 构建链（package.json）"
node -e "
const p=require('${CAPGO_REPO}/package.json');
const d={...p.dependencies,...p.devDependencies};
const keys=['vite','vue','typescript','@supabase/supabase-js','supabase','@capgo/capacitor-updater','@capacitor/core'];
console.log('| 包 | 版本 |');
console.log('| --- | --- |');
for (const k of keys) if (d[k]) console.log('| '+k+' | \`'+d[k]+'\` |');
" 2>/dev/null || echo "(需要 node 解析 package.json)"

log_section "运行中容器（docker compose images）"
if [[ -f "$COMPOSE" ]]; then
  (cd "$SUPABASE_PROJECT_DIR" && docker compose images 2>/dev/null) || echo "docker compose images 失败"
else
  echo "跳过"
fi

printf '\n> 完整说明见 docs/self-hosted-version-pins.zh-CN.md\n'
